default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: main_app_development
  username: postgres
  password: postgres
  host: localhost

  # database: <%= ENV["DATABASE_NAME"] %>
  # username: <%= ENV["DATABASE_USER"] %>
  # password: <%= ENV["DATABASE_PASSWORD"] %>
  # host: <%= ENV['DATABASE_HOST'] %>
  # port: <%= ENV['DATABASE_PORT'] %>
  # sslmode: require

test:
  <<: *default
  database: main_app_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  # database: <%= ENV["DATABASE_NAME"] %>
  # username: <%= ENV["DATABASE_USER"] %>
  # password: <%= ENV["DATABASE_PASSWORD"] %>
  # host: <%= ENV['DATABASE_HOST'] %>
  # port: <%= ENV['DATABASE_PORT'] %>
